services:
  netflow2ng:
    build: .
    container_name: netflow2ng
    restart: unless-stopped
    entrypoint: /netflow2ng
    command: ["--metrics=0.0.0.0:8081"]
    network_mode: host

  redis:
    image: "redis:alpine"
    network_mode: host

  ntopng:
    image: "ntop/ntopng:latest"
    command: ["--community", "--redis", "localhost", "--interface", "tcp://localhost:5556", "--local-networks", "192.168.1.0/24", "-w", "3001"]
    network_mode: host
    depends_on:
      - netflow2ng
      - redis
