services:
  netflow2ng:
    build: . # make sure to clone the whole repository
    container_name: netflow2ng
    restart: unless-stopped
    entrypoint: /netflow2ng # --level=debug
    # network mode must be host due to source port changing for inbound netflow packets with NAT
    network_mode: host

  redis:
    image: "redis:alpine"
    network_mode: host

  ntopng:
    image: "ntop/ntopng:latest"
    command: ["--community", "--redis", "localhost", "--interface", "tcp://localhost:5556", "--local-networks", "192.168.1.0/24"]
    network_mode: host
    depends_on:
      - netflow2ng
      - redis
